dacs_sv5t/Models/SINHVIEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.DUYET_TC = new HashSet<DUYET_TC>();
            this.MINHCHUNGs = new HashSet<MINHCHUNG>();
        }
    
        public int ID_SV { get; set; }
        public string TEN_SV { get; set; }
        public string LOP { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public int ID_KV { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> MSSV { get; set; }
        public Nullable<int> ID_CAP { get; set; }
    
        public virtual CAP CAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUYET_TC> DUYET_TC { get; set; }
        public virtual KHOAVIEN KHOAVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MINHCHUNG> MINHCHUNGs { get; set; }
    }
}

dacs_sv5t/Areas/admin/Controllers/SinhVienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DACS_SV5T.Models;

namespace DACS_SV5T.Areas.admin.Controllers
{
    public class SinhVienController : Controller
    {
        private DACS_SV5TEntities db = new DACS_SV5TEntities();

        // GET: admin/SinhVien
        public ActionResult Index(long? KhoaVien = null, long? Cap = null)
        {
            //var sINHVIENs = db.SINHVIENs.Include(s => s.KHOAVIEN).Include(s => s.CAP);
            getKhoa(KhoaVien);
            getCap(Cap);
            return View();
        }

        public void getKhoa(long? selectedId = null)
        {
            ViewBag.KhoaVien = new SelectList(db.KHOAVIENs, "ID_KV", "TEN_KV", selectedId);
        }
        public void getCap(long? selectedId = null)
        {
            ViewBag.Cap = new SelectList(db.CAPs, "ID_CAP", "TEN_CAP", selectedId);
        }
        public ActionResult getSinhVien(long? id1, long? id2)
        {
            var SinhVien = db.SINHVIENs;
            var Khoa = db.KHOAVIENs;
            var Cap = db.CAPs;
            if (id1 == null && id2 ==null)
            {
                var v = db.SINHVIENs.ToList();
                return PartialView(v);
            }
            if (id1 != null && id2 == null)
            {
                var n = from a in SinhVien
                        join b in Khoa on a.ID_KV equals b.ID_KV
                        join c in Cap on a.ID_CAP equals c.ID_CAP
                        where b.ID_KV == id1
                        select a;
                return PartialView(n.ToList());
            }
            if (id1 == null && id2 != null)
            {
                var o = from a in SinhVien
                        join b in Khoa on a.ID_KV equals b.ID_KV
                        join c in Cap on a.ID_CAP equals c.ID_CAP
                        where c.ID_CAP == id2
                        select a;
                return PartialView(o.ToList());
            }
            var m = from a in SinhVien
                    join b in Khoa on a.ID_KV equals b.ID_KV
                    join c in Cap on a.ID_CAP equals c.ID_CAP
                    where b.ID_KV == id1 && c.ID_CAP == id2
                    select a;
            return PartialView(m);
        }
        // GET: admin/SinhVien/Details/5
        public ActionResult Details(int? id)
        {
            Session["Detail_ID_SV"] = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            Edit(id);
            return View(sINHVIEN);
        }

        // GET: admin/SinhVien/Create
        public ActionResult Create()
        {
            ViewBag.ID_KV = new SelectList(db.KHOAVIENs, "ID_KV", "TEN_KV");
            ViewBag.ID_CAP = new SelectList(db.CAPs, "ID_CAP", "TEN_CAP");
            return View();
        }

        // POST: admin/SinhVien/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SV,TEN_SV,LOP,DIACHI,EMAIL,SDT,ID_KV,PASSWORD,MSSV,ID_CAP")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                db.SINHVIENs.Add(sINHVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_KV = new SelectList(db.KHOAVIENs, "ID_KV", "TEN_KV", sINHVIEN.ID_KV);
            ViewBag.ID_CAP = new SelectList(db.CAPs, "ID_CAP", "TEN_CAP", sINHVIEN.ID_CAP);
            return View(sINHVIEN);
        }

        // GET: admin/SinhVien/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_KV = new SelectList(db.KHOAVIENs, "ID_KV", "TEN_KV", sINHVIEN.ID_KV);
            ViewBag.ID_CAP = new SelectList(db.CAPs, "ID_CAP", "TEN_CAP", sINHVIEN.ID_CAP);
            return View(sINHVIEN);
        }

        // POST: admin/SinhVien/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SV,TEN_SV,LOP,DIACHI,EMAIL,SDT,ID_KV,PASSWORD,MSSV,ID_CAP")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sINHVIEN).State = EntityState.Modified;
                db.SaveChanges();

            }
            ViewBag.ID_KV = new SelectList(db.KHOAVIENs, "ID_KV", "TEN_KV", sINHVIEN.ID_KV);
            ViewBag.ID_CAP = new SelectList(db.CAPs, "ID_CAP", "TEN_CAP", sINHVIEN.ID_CAP);
            return View(sINHVIEN);
        }

        // GET: admin/SinhVien/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            return View(sINHVIEN);
        }

        // POST: admin/SinhVien/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            db.SINHVIENs.Remove(sINHVIEN);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dacs_sv5t/Controllers/SinhVienController.cs
using DACS_SV5T.Help;
using DACS_SV5T.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DACS_SV5T.Controllers
{
    public class SinhVienController : Controller
    {
        DACS_SV5TEntities _db = new DACS_SV5TEntities();
        // GET: SinhVien
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(long mssv, string password)
        {
            string passwordMD5 = Common.EncryptMD5(mssv + password);
            var user = _db.SINHVIENs.SingleOrDefault(x => x.MSSV == mssv && x.PASSWORD == passwordMD5);
            if (user != null)
            {
                Session["ID_SV"] = user.ID_SV;
                Session["TEN_SV"] = user.TEN_SV;
                Session["MSSV"] = user.MSSV;
                Session["LOP"] = user.LOP;
                Session["DIACHI"] = user.DIACHI;
                Session["EMAIL"] = user.EMAIL;
                Session["SDT"] = user.SDT;
                Session["ID_KV"] = user.ID_KV;
                Session["PASSWORD"] = user.PASSWORD;
                return RedirectToAction("Index", "Default");
            }
            ViewBag.error = "Đăng nhập thất bại";
            return View();
        }

        public ActionResult DangXuat()
        {
            Session["ID_SV"] = null;
            Session["TEN_SV"] = null;
            Session["MSSV"] = null;
            Session["LOP"] = null;
            Session["DIACHI"] = null;
            Session["EMAIL"] = null;
            Session["SDT"] = null;
            Session["ID_KV"] = null;
            Session["PASSWORD"] = null;
            return RedirectToAction("Index", "Default");
        }

        public ActionResult ThongTinSV()
        {
            var id = Session["ID_SV"];
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = _db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_KV = new SelectList(_db.KHOAVIENs, "ID_KV", "TEN_KV", sINHVIEN.ID_KV);
            ViewBag.ID_CAP = new SelectList(_db.CAPs, "ID_CAP", "TEN_CAP", sINHVIEN.ID_CAP);
            return View(sINHVIEN);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThongTinSV([Bind(Include = "ID_SV,TEN_SV,LOP,DIACHI,EMAIL,SDT,ID_KV,PASSWORD,MSSV,ID_CAP")] SINHVIEN sINHVIEN)
        {
            var password = Session["PASSWORD"];
            if (ModelState.IsValid)
            {
                sINHVIEN.PASSWORD = (string)password;
                _db.Entry(sINHVIEN).State = EntityState.Modified;
                _db.SaveChanges();
                ViewBag.success = "Cập nhật thông tin thành công";
            }
            ViewBag.ID_KV = new SelectList(_db.KHOAVIENs, "ID_KV", "TEN_KV", sINHVIEN.ID_KV);
            ViewBag.ID_CAP = new SelectList(_db.CAPs, "ID_CAP", "TEN_CAP", sINHVIEN.ID_CAP);
            return View(sINHVIEN);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

dacs_sv5t/Areas/admin/Views/SinhVien/Create.cshtml
@model DACS_SV5T.Models.SINHVIEN
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}
<div style="height:15px"></div>
<div class="panel panel-red">
    <div class="panel-heading">Thêm Bài viết mới</div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TEN_SV,"Tên sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TEN_SV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TEN_SV, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LOP,"Lớp", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LOP, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LOP, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DIACHI,"Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.EMAIL,"Email", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SDT,"SĐT", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ID_KV, "ID_KV", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ID_KV", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_KV, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PASSWORD,"Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.MSSV,"MSSV", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MSSV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MSSV, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ID_CAP, "ID_CAP", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ID_CAP", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_CAP, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Lưu" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Quay về", "Index", "Index", new { @class = "btn btn-success" })
        </div>
    </div>
</div>
@section _footer
{
    <script src="~/Areas/admin/Content/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/admin/Content/ckeditor/ckeditor.js"></script>

    <script type="text/javascript">
        var editor = CKEDITOR.replace("DETAIL");
        var editor = CKEDITOR.replace("DETAIL", { height: '600px' });
        customConfig: '/Areas/admin/Content/ckeditor/config.js';
    </script>

}

dacs_sv5t/Areas/admin/Views/SinhVien/Delete.cshtml
@model DACS_SV5T.Models.SINHVIEN

@{
    ViewBag.Title = "Xóa sinh viên";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<style>
    dt, dd {
        margin-bottom: 5px;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red" style="margin-top:20px">
            <div class="panel-heading">
                Bạn có muốn xóa sinh viên : @Html.DisplayFor(model => model.TEN_SV)
            </div>

            <!-- /.panel-heading -->
            <div class="panel-body">
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Họ và tên sinh viên :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TEN_SV)
                    </dd>

                    <dt>
                        Lớp :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LOP)
                    </dd>

                    <dt>
                        Địa chỉ : 
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DIACHI)
                    </dd>

                    <dt>
                        Email :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.EMAIL)
                    </dd>

                    <dt>
                        Số điện thoại
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SDT)
                    </dd>

                    <dt>
                        Mã số sinh viên :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MSSV)
                    </dd>

                    <dt>
                        Khoa/Viện :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.KHOAVIEN.TEN_KV)
                    </dd>

                    <dt>
                        Cấp độ SV5T :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CAP.TEN_CAP)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Xóa" class="btn btn-danger" /> |
                        @Html.ActionLink("Quay về", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->

dacs_sv5t/Areas/admin/Views/SinhVien/Details.cshtml
@model DACS_SV5T.Models.SINHVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}
<style>
        dt, dd {
            margin-bottom:5px;
        }
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red" style="margin-top:20px">
            <div class="panel-heading">
                Chi tiết sinh viên : @Html.DisplayFor(model => model.TEN_SV)
            </div>
            
            <!-- /.panel-heading -->
            <div class="panel-body">
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Họ và tên sinh viên :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TEN_SV)
                    </dd>
                    <dt>
                        Mã số sinh viên :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MSSV)
                    </dd>

                    <dt>
                        Lớp :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LOP)
                    </dd>
                    <dt>
                        Khoa/Viện :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.KHOAVIEN.TEN_KV)
                    </dd>
                    <dt>
                        Địa chỉ :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DIACHI)
                    </dd>

                    <dt>
                        Email :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.EMAIL)
                    </dd>

                    <dt>
                        Số điện thoại :
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SDT)
                    </dd>
                    <dt>
                        Cấp độ SV5T :
                    </dt>

                    <dd>
                        @{ Html.RenderAction("Edit", "SinhVien");}
                    </dd>

                </dl>
                
                <div style="width:80%; margin-left:20px">
                    <hr />
                    @{ Html.RenderAction("LoaiTieuChi", "HoatDongAdmin");}
                </div>

            </div>
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->

dacs_sv5t/Areas/admin/Views/SinhVien/Index.cshtml
@using DACS_SV5T.Help
@model Tuple<DACS_SV5T.Models.KHOAVIEN, DACS_SV5T.Models.CAP>

@{
    ViewBag.Title = "Danh sách sinh viên";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

@section _Header
{
    <!-- DataTables CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red" style="margin-top:20px">
            <div class="panel-heading">
                Quản lý sinh viên
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="bs-example" style="text-align:right; padding-bottom:10px;">
                    <div class="btn-group">
                        @Html.DropDownListFor(Tuple => Tuple.Item1.ID_KV, (SelectList)ViewBag.KhoaVien, " --- Tất cả khoa --- ",
                                                                        new { @class = "form-control", @id = "KhoaVien" })
                    </div>
                    <div class="btn-group">
                        @Html.DropDownListFor(Tuple => Tuple.Item2.ID_CAP, (SelectList)ViewBag.Cap, " --- Tất cả cấp --- ",
                                                                        new { @class = "form-control", @id = "Cap" })
                    </div>
                    <div class="btn-group">
                        @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span> Thêm mới", "Create", "Create", "SinhVien", routeValues: new { }, htmlAttributes: new { @class = "btn btn-primary" })
                    </div>
                </div>
                <div id="getSinhVien"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@section _Footer
{
    <!-- DataTables JavaScript -->
    <script src="/Areas/admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script>
        $(document).ready(function () {
            function getKhoa() {
                var ID_KV = $('#KhoaVien').val();
                var ID_CAP = $('#Cap').val();
                $.ajax({
                    url: '@Url.Action("getSinhVien", "SinhVien")',
                    type: "GET",
                    data: { id1: ID_KV, id2: ID_CAP },
                    success: function (data) {
                        $("#getSinhVien").html(data);
                    },
                    error: function (data) {
                        alert("something went wrong.");
                    }
                });
            }
            getKhoa();
            $("#KhoaVien").change(function () {
                getKhoa();
            })
            $("#Cap").change(function () {
                getKhoa();
            })
        });
    </script>
}

dacs_sv5t/Areas/admin/Views/SinhVien/getSinhVien.cshtml
@using DACS_SV5T.Help
@model IEnumerable<DACS_SV5T.Models.SINHVIEN>
<style>
    th, td {
        text-align: center;
    }

        td p {
            height: 50px;
            overflow-y: hidden;
            text-overflow: ellipsis;
        }
</style>
<table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width:100%">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                Tên sinh viên
            </th>
            <th>
                Lớp
            </th>
            <th>
                Mã số sinh viên
            </th>
            <th>
                Cấp đã đạt
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{var Number = 1; }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(Number++)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TEN_SV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LOP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MSSV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CAP.TEN_CAP)
                </td>
                <td>
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-zoom-in'></span>", "Detail", "Details", "SinhVien", routeValues: new { id = item.ID_SV }, htmlAttributes: new { @class = "btn btn-primary" })
                    @if (Convert.ToBoolean(Session["PQ"]) == true)
                    {
                        @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Delete", "Delete", "SinhVien", routeValues: new { id = item.ID_SV }, htmlAttributes: new { @class = "btn btn-danger" })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "Không có dữ liệu trong bảng",
                "info": "Hiển thị _START_ tới _END_ ",
                "infoEmpty": "Hiển thị 0 đến 0 của 0 danh sách",
                "infoFiltered": "(Lọc từ _MAX_ danh sách)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Hiển _MENU_ danh sách",
                "loadingRecords": "Đang tải...",
                "processing": "Đang xử lý...",
                "search": "Tìm kiếm:",
                "zeroRecords": "Không tìm thấy",
                "paginate": {
                    "first": "Trang đầu",
                    "last": "Cuối cùng",
                    "next": "Trang sau",
                    "previous": "Trang trước"
                },
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                }
            }
        });
    });
</script>