dacs_sv5t/Models/LOAITIEUCHI.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITIEUCHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITIEUCHI()
        {
            this.TIEUCHIs = new HashSet<TIEUCHI>();
        }
    
        public int ID_LTCHI { get; set; }
        public string TEN_LTCHI { get; set; }
        public Nullable<int> NAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIEUCHI> TIEUCHIs { get; set; }
    }
}

dacs_sv5t/Models/TIEUCHI.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIEUCHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIEUCHI()
        {
            this.CT_TEUCHI = new HashSet<CT_TEUCHI>();
        }
    
        public int ID_TCHI { get; set; }
        public string TEN_TCHI { get; set; }
        public int ID_LTCHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TEUCHI> CT_TEUCHI { get; set; }
        public virtual LOAITIEUCHI LOAITIEUCHI { get; set; }
    }
}

dacs_sv5t/Areas/admin/Controllers/HoatDongAdminController.cs
using DACS_SV5T.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DACS_SV5T.Areas.admin.Controllers
{
    public class HoatDongAdminController : Controller
    {
        // GET: admin/HoatDong
        DACS_SV5TEntities _db = new DACS_SV5TEntities();
        // GET: HoatDong
        public ActionResult LoaiTieuChi()
        {
            var TieuChi = _db.LOAITIEUCHIs;
            var v = from t in TieuChi
                    select t;
            return View(v.ToList());
        }
        public ActionResult CTTieuChi(int LTC, int IDTC)
        {
            var TieuChi = _db.TIEUCHIs;
            var ChiTietTC = _db.CT_TEUCHI;
            var v = from t in TieuChi
                    join l in ChiTietTC
                    on t.ID_TCHI equals l.ID_TCHI
                    where t.ID_LTCHI == LTC && l.ID_TCHI == IDTC
                    select l;
            return PartialView(v.ToList());
        }
        public ActionResult TieuChi(int LTC)
        {
            var TieuChi = _db.TIEUCHIs;
            var v = from t in TieuChi
                    where t.ID_LTCHI == LTC
                    select t;
            return View(v.ToList());
        }

        public ActionResult HinhTieuChi(int? ID_CTTCHI)
        {
            var ID_SV = Session["Detail_ID_SV"];
            if (ID_SV == null && ID_CTTCHI == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MINHCHUNG mINHCHUNG = _db.MINHCHUNGs.Find(ID_SV, ID_CTTCHI);
            if (mINHCHUNG == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_CTTCHI = new SelectList(_db.CT_TEUCHI, "ID_CTTCHI", "NOIDUNG", mINHCHUNG.ID_CTTCHI);
            ViewBag.ID_SV = new SelectList(_db.SINHVIENs, "ID_SV", "TEN_SV", mINHCHUNG.ID_SV);
            return View(mINHCHUNG);
        }

        public bool CheckID_SV(int ID_SV)
        {
            return _db.MINHCHUNGs.Count(x => x.ID_SV == ID_SV) > 0;
        }
        public bool CheckID_CTTC(int ID_CTTC)
        {
            return _db.MINHCHUNGs.Count(x => x.ID_CTTCHI == ID_CTTC) > 0;
        }

        public ActionResult QuanLyMinhChung(int? ID_CTTCHI)
        {
            var id = Session["ID_SV"];
            if (id == null && ID_CTTCHI == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = _db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_CTTCHI = new SelectList(_db.CT_TEUCHI, "ID_CTTCHI", "NOIDUNG", ID_CTTCHI);
            ViewBag.ID_SV = new SelectList(_db.SINHVIENs, "ID_SV", "TEN_SV", sINHVIEN.ID_SV);
            return View();
        }
        
    }
}

dacs_sv5t/Areas/admin/Controllers/TieuChiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DACS_SV5T.Models;

namespace DACS_SV5T.Areas.admin.Controllers
{
    public class TieuChiController : Controller
    {
        private DACS_SV5TEntities db = new DACS_SV5TEntities();

        // GET: admin/TieuChi
        public ActionResult Index()
        {
            return View(db.LOAITIEUCHIs.ToList());
        }

        // GET: admin/TieuChi/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/TieuChi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_LTCHI,TEN_LTCHI,NAM")] LOAITIEUCHI lOAITIEUCHI)
        {
            if (ModelState.IsValid)
            {
                db.LOAITIEUCHIs.Add(lOAITIEUCHI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lOAITIEUCHI);
        }

        // GET: admin/TieuChi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAITIEUCHI lOAITIEUCHI = db.LOAITIEUCHIs.Find(id);
            if (lOAITIEUCHI == null)
            {
                return HttpNotFound();
            }
            return View(lOAITIEUCHI);
        }

        // POST: admin/TieuChi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_LTCHI,TEN_LTCHI,NAM")] LOAITIEUCHI lOAITIEUCHI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lOAITIEUCHI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lOAITIEUCHI);
        }

        // GET: admin/TieuChi/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAITIEUCHI lOAITIEUCHI = db.LOAITIEUCHIs.Find(id);
            if (lOAITIEUCHI == null)
            {
                return HttpNotFound();
            }
            return View(lOAITIEUCHI);
        }

        // POST: admin/TieuChi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LOAITIEUCHI lOAITIEUCHI = db.LOAITIEUCHIs.Find(id);
            try
            {
                db.LOAITIEUCHIs.Remove(lOAITIEUCHI);
            db.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                ViewBag.error = "Không thể xóa";
                return View(lOAITIEUCHI);
            }
            catch (Exception ex)
            {
                ViewBag.error = "Không thể xóa";
                return View(lOAITIEUCHI);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dacs_sv5t/Areas/admin/Views/HoatDongAdmin/CTTieuChi.cshtml
@model List<DACS_SV5T.Models.CT_TEUCHI>
<style>
    th, td {
        text-align: center;
    }

        td p {
            height: 50px;
            overflow-y: hidden;
            text-overflow: ellipsis;
        }
</style>
@section _Header
{
    <!-- DataTables CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
}
<table class="table-bordered table-hover" id="dataTables-example" style="width:100%;">
   
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NOIDUNG)
                </td>
                <td width="20%" style="text-align:center; vertical-align:middle; max-width:30%">
                    @Html.Action("HinhTieuChi", "HoatDongAdmin", new { ID_CTTCHI = item.ID_CTTCHI })
                </td>
            </tr>
        }
    </tbody>

</table>

@section _Footer
{
    <!-- DataTables JavaScript -->
    <script src="/Areas/admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true,
                "language": {
                    "decimal": "",
                    "emptyTable": "Không có dữ liệu trong bảng",
                    "info": "Hiển thị _START_ tới _END_ ",
                    "infoEmpty": "Hiển thị 0 đến 0 của 0 danh sách",
                    "infoFiltered": "(Lọc từ _MAX_ danh sách)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Hiển _MENU_ danh sách",
                    "loadingRecords": "Đang tải...",
                    "processing": "Đang xử lý...",
                    "search": "Tìm kiếm:",
                    "zeroRecords": "Không tìm thấy",
                    "paginate": {
                        "first": "Trang đầu",
                        "last": "Cuối cùng",
                        "next": "Trang sau",
                        "previous": "Trang trước"
                    },
                    "aria": {
                        "sortAscending": ": activate to sort column ascending",
                        "sortDescending": ": activate to sort column descending"
                    }
                }
            });
        });
    </script>

}

dacs_sv5t/Areas/admin/Views/HoatDongAdmin/HinhTieuChi.cshtml
@model DACS_SV5T.Models.MINHCHUNG

    <img data-toggle="modal" data-target=".@Model.ID_CTTCHI-bootstrapmodal" src="~/Content/upload/minhchung/@Model.HINHANH" style='width: 100%; object-fit: cover' class="img-responsive" />
    <div class="modal fade @Model.ID_CTTCHI-bootstrapmodal">
        <div class="modal-dialog" style="width:50%; height:40%;max-width:500px;max-height:500px">
            <div class="modal-content">
                <div class="modal-header">
                    <button data-dismiss="modal" class="close"><span>&times;</span></button>
                    <div class="modal-title" style="text-align:center"><h4>Xem minh chứng</h4></div>
                </div>
                <div class="modal-body">
                    <img src="~/Content/upload/minhchung/@Model.HINHANH" style='width: 100%; object-fit: cover' class="img-responsive" />
                </div>
            </div>
        </div>
    </div>

dacs_sv5t/Areas/admin/Views/HoatDongAdmin/LoaiTieuChi.cshtml
@model IEnumerable<DACS_SV5T.Models.LOAITIEUCHI>
<div class="panel-group" id="accordion">
    @foreach (var item in Model)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#@item.ID_LTCHI-LTC">
                        @Html.DisplayFor(modelItem => item.TEN_LTCHI)
                    </a>
                </h4>
            </div>
            <div id="@item.ID_LTCHI-LTC" class="panel-collaps ">
                <div class="panel-body">
                    <!--/*Html.Action("CTTieuChi", "HoatDong", new { LTC = //item.ID_LTCHI})*/
    //-->
                    @Html.Action("TieuChi", "HoatDongAdmin", new { LTC = item.ID_LTCHI })
                </div>
            </div>
        </div>
    }
</div>

dacs_sv5t/Areas/admin/Views/HoatDongAdmin/TieuChi.cshtml
@model IEnumerable<DACS_SV5T.Models.TIEUCHI>

<div class="panel-group" id="accordionTieuChi">
    @foreach (var item in Model)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordionTieuChi" href="#@item.ID_TCHI-TieuChi">
                        @Html.DisplayFor(modelItem => item.TEN_TCHI)
                    </a>
                </h4>
            </div>
            <div id="@item.ID_TCHI-TieuChi" class="panel-collapse ">
                <div class="panel-body">
                    @Html.Action("CTTieuChi", "HoatDongAdmin", new { LTC = @item.ID_LTCHI, IDTC = @item.ID_TCHI })
                </div>
            </div>
        </div>
    }
</div>