dacs_sv5t/Areas/admin/Controllers/YeuCauController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DACS_SV5T.Models;

namespace DACS_SV5T.Areas.admin.Controllers
{
    public class YeuCauController : Controller
    {
        private DACS_SV5TEntities db = new DACS_SV5TEntities();

        // GET: admin/YeuCau
        public ActionResult Index(long? ID_LTCHI = null)
        {
            getTieuChi(ID_LTCHI);
            return View();
        }
        public void getTieuChi(long? selectedId = null)
        {
            ViewBag.YeuCau = new SelectList(db.LOAITIEUCHIs, "ID_LTCHI", "TEN_LTCHI", selectedId);
        }

        public ActionResult getYeuCau(long? id)
        {
            if (id == null)
            {
                var v = db.TIEUCHIs.ToList();
                return PartialView(v);
            }
            var m = db.TIEUCHIs.Where(x => x.ID_LTCHI == id).ToList();
            return PartialView(m);
        }

        // GET: admin/YeuCau/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIEUCHI tIEUCHI = db.TIEUCHIs.Find(id);
            if (tIEUCHI == null)
            {
                return HttpNotFound();
            }
            return View(tIEUCHI);
        }

        // GET: admin/YeuCau/Create
        public ActionResult Create()
        {
            ViewBag.ID_LTCHI = new SelectList(db.LOAITIEUCHIs, "ID_LTCHI", "TEN_LTCHI");
            return View();
        }

        // POST: admin/YeuCau/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_TCHI,TEN_TCHI,ID_LTCHI")] TIEUCHI tIEUCHI)
        {
            if (ModelState.IsValid)
            {
                db.TIEUCHIs.Add(tIEUCHI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_LTCHI = new SelectList(db.LOAITIEUCHIs, "ID_LTCHI", "TEN_LTCHI", tIEUCHI.ID_LTCHI);
            return View(tIEUCHI);
        }

        // GET: admin/YeuCau/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIEUCHI tIEUCHI = db.TIEUCHIs.Find(id);
            if (tIEUCHI == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_LTCHI = new SelectList(db.LOAITIEUCHIs, "ID_LTCHI", "TEN_LTCHI", tIEUCHI.ID_LTCHI);
            return View(tIEUCHI);
        }

        // POST: admin/YeuCau/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_TCHI,TEN_TCHI,ID_LTCHI")] TIEUCHI tIEUCHI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tIEUCHI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_LTCHI = new SelectList(db.LOAITIEUCHIs, "ID_LTCHI", "TEN_LTCHI", tIEUCHI.ID_LTCHI);
            return View(tIEUCHI);
        }

        // GET: admin/YeuCau/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIEUCHI tIEUCHI = db.TIEUCHIs.Find(id);
            if (tIEUCHI == null)
            {
                return HttpNotFound();
            }
            return View(tIEUCHI);
        }

        // POST: admin/YeuCau/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TIEUCHI tIEUCHI = db.TIEUCHIs.Find(id);
            try
            {
                
            db.TIEUCHIs.Remove(tIEUCHI);
            db.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                ViewBag.error = "Không thể xóa";
                return View(tIEUCHI);
            }
            catch (Exception ex)
            {
                ViewBag.error = "Không thể xóa";
                return View(tIEUCHI);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dacs_sv5t/Areas/admin/Views/YeuCau/Create.cshtml
@model DACS_SV5T.Models.TIEUCHI

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TIEUCHI</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TEN_TCHI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_TCHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEN_TCHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_LTCHI, "ID_LTCHI", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_LTCHI", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_LTCHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

dacs_sv5t/Areas/admin/Views/YeuCau/Delete.cshtml
@model DACS_SV5T.Models.TIEUCHI

@{
    ViewBag.Title = "Xóa yêu cầu";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red" style="margin-top:20px">
            <div class="panel-heading">
                Bạn có muốn xóa @Html.DisplayFor(model => model.TEN_TCHI)
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <h4 style="color:red">@ViewBag.error</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Loại yêu cầu
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TEN_TCHI)
                    </dd>

                    <dt>
                        Loại tiêu chí
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LOAITIEUCHI.TEN_LTCHI)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Xóa" class="btn btn-danger" /> |
                        @Html.ActionLink("Quay về", "Index")
                    </div>
                }
            </div>

        </div>
    </div>
</div>

dacs_sv5t/Areas/admin/Views/YeuCau/Details.cshtml
@model DACS_SV5T.Models.TIEUCHI

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TIEUCHI</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TEN_TCHI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEN_TCHI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LOAITIEUCHI.TEN_LTCHI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOAITIEUCHI.TEN_LTCHI)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_TCHI }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dacs_sv5t/Areas/admin/Views/YeuCau/Edit.cshtml
@model DACS_SV5T.Models.TIEUCHI

@{
    ViewBag.Title = "Chỉnh sửa yêu cầu";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red" style="margin-top:20px">
            <div class="panel-heading">
                Chỉnh sửa tiêu chí
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID_TCHI)

                        <div class="form-group">
                            @Html.Label("Loại yêu cầu", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TEN_TCHI, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TEN_TCHI, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Tên tiêu chí", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_LTCHI", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ID_LTCHI, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Lưu" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Quay về", "Index")
                </div>

            </div>
        </div>
    </div>
</div>

dacs_sv5t/Areas/admin/Views/YeuCau/Index.cshtml
@using DACS_SV5T.Help
@model DACS_SV5T.Models.LOAITIEUCHI

@{
    ViewBag.Title = "Yêu cầu";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

@section _Header
{
    <!-- DataTables CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red" style="margin-top:20px">
            <div class="panel-heading">
                Quản lý yêu cầu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @if (Convert.ToBoolean(Session["PQ"]) == true)
                {
                    <div class="bs-example" style="text-align:right; padding-bottom:10px;">
                        <div class="btn-group">
                            @Html.DropDownListFor(model => model.ID_LTCHI, (SelectList)ViewBag.YeuCau, " --- Tất cả tiêu chí --- ",
                                                                         new { @class = "form-control", @id = "TieuChi" })
                        </div>
                        <div class="btn-group">
                            @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span> Thêm mới", "Create", "Create", "YeuCau", routeValues: new { }, htmlAttributes: new { @class = "btn btn-primary" })
                        </div>
                    </div>
                }
                    <div id="getYeuCau"></div>
                </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@section _Footer
{
    <!-- DataTables JavaScript -->
    <script src="/Areas/admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script>
        $(document).ready(function () {
            function getYeuCau() {
                var ID_LTCHI = $('#TieuChi').val();
                $.ajax({
                    url: '@Url.Action("getYeuCau", "YeuCau")',
                    type: "GET",
                    data: { id: ID_LTCHI},
                    success: function (data) {
                        $("#getYeuCau").html(data);
                    },
                    error: function (data) {
                        alert("something went wrong.");
                    }
                });
            }
            getYeuCau();
            $("#TieuChi").change(function () {
                getYeuCau();
            })
        });
    </script>
}

dacs_sv5t/Areas/admin/Views/YeuCau/getYeuCau.cshtml
@using DACS_SV5T.Help
@model IEnumerable<DACS_SV5T.Models.TIEUCHI>

<style>
    th, td {
        text-align: center;
    }

        td p {
            height: 50px;
            overflow-y: hidden;
            text-overflow: ellipsis;
        }
</style>
<table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width:100%">
    <thead>

        <tr>
            <th>
                STT
            </th>
            <th>
                Loại yêu cầu
            </th>
            <th>
                Tên tiêu chí
            </th>
            @if (Convert.ToBoolean(Session["PQ"]) == true)
            {
                <th></th>
            }
            </tr>
    </thead>
    <tbody>
        @{var Number = 1; }
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.Raw(Number++)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TEN_TCHI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LOAITIEUCHI.TEN_LTCHI)
            </td>
            @if (Convert.ToBoolean(Session["PQ"]) == true)
            {
                <td>
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Edit", "Edit", "YeuCau", routeValues: new { id = item.ID_TCHI }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Delete", "Delete", "YeuCau", routeValues: new { id = item.ID_TCHI }, htmlAttributes: new { data_modal = "", @class = "btn btn-danger" })

                </td>
            }
            </tr>
        }
        </tbody>
</table>

<script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true,
                "language": {
                    "decimal": "",
                    "emptyTable": "Không có dữ liệu trong bảng",
                    "info": "Hiển thị _START_ tới _END_ ",
                    "infoEmpty": "Hiển thị 0 đến 0 của 0 danh sách",
                    "infoFiltered": "(Lọc từ _MAX_ danh sách)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Hiển _MENU_ danh sách",
                    "loadingRecords": "Đang tải...",
                    "processing": "Đang xử lý...",
                    "search": "Tìm kiếm:",
                    "zeroRecords": "Không tìm thấy",
                    "paginate": {
                        "first": "Trang đầu",
                        "last": "Cuối cùng",
                        "next": "Trang sau",
                        "previous": "Trang trước"
                    },
                    "aria": {
                        "sortAscending": ": activate to sort column ascending",
                        "sortDescending": ": activate to sort column descending"
                    }
                }
            });
        });
</script>